import json
import os

# Variável global para gerenciar IDs únicos
global proximo_id
proximo_id = 1

class Cultura:
    def __init__(
        self,
        nome,
        tipo,
        classificacao_agronomica=None,
        classificacao_morfologica=None,
        sinergias=None,
        antagonismos=None,
        tempo_crescimento=0,
        rendimento=0,
        necessidades=None,
        necessidade_luz=None,
        necessidade_hidrica=None,
        temperatura_ideal=None,
        faixa_ph=None,
        porte=None,
        ciclo=None,
        epocas_plantio=None,
        exigencia_nutricional=None,
        sombreamento=0,
        pragas=None,
        doencas=None,
        controle_natural=None,
        cobertura_solo=1,
        diametro_copa=1,  # Novo atributo adicionado
        atrai_polinizadores=None,
        interacao_outros=None,
        resistencia=None,
        tempo_colheita=None,
        icone="?",
        **kwargs
    ):
        global proximo_id
        self.id_cultura = proximo_id
        proximo_id += 1

        self.nome = nome
        self.tipo = tipo
        # Categoria explícita: Frutífera, Hortaliça ou Roça
        lower_tipo = (tipo or "").lower()
        if 'frut' in lower_tipo:
            self.categoria = 'Frutífera'
        elif 'hort' in lower_tipo:
            self.categoria = 'Hortaliça'
        else:
            self.categoria = 'Roça'

        self.classificacao_agronomica = classificacao_agronomica or "Não especificado"
        self.classificacao_morfologica = classificacao_morfologica or "Não especificado"
        self.sinergias = sinergias or []
        self.antagonismos = antagonismos or []
        self.tempo_crescimento = tempo_crescimento
        self.rendimento = rendimento
        self.necessidades = necessidades or {"sol": "moderado", "agua": "moderado", "solo": "neutro"}
        self.necessidade_luz = necessidade_luz
        self.necessidade_hidrica = necessidade_hidrica
        self.temperatura_ideal = temperatura_ideal
        self.faixa_ph = faixa_ph
        self.porte = porte
        self.ciclo = ciclo
        self.epocas_plantio = epocas_plantio
        self.exigencia_nutricional = exigencia_nutricional
        self.sombreamento = int(sombreamento)
        self.pragas = pragas or []
        self.doencas = doencas or []
        self.controle_natural = controle_natural or []
        self.cobertura_solo = int(cobertura_solo)
        self.diametro_copa = int(diametro_copa)  # Atributo novo
        self.atrai_polinizadores = atrai_polinizadores
        self.interacao_outros = interacao_outros
        self.resistencia = resistencia
        self.tempo_colheita = tempo_colheita
        self.icone = icone
        self.atributos_extras = kwargs
        self.idade = 0
        self.saudavel = True

    def to_dict(self):
        return {
            "id_cultura": self.id_cultura,
            "nome": self.nome,
            "tipo": self.tipo,
            "categoria": self.categoria,
            "classificacao_agronomica": self.classificacao_agronomica,
            "classificacao_morfologica": self.classificacao_morfologica,
            "sinergias": self.sinergias,
            "antagonismos": self.antagonismos,
            "tempo_crescimento": self.tempo_crescimento,
            "rendimento": self.rendimento,
            "necessidades": self.necessidades,
            "necessidade_luz": self.necessidade_luz,
            "necessidade_hidrica": self.necessidade_hidrica,
            "temperatura_ideal": self.temperatura_ideal,
            "faixa_ph": self.faixa_ph,
            "porte": self.porte,
            "ciclo": self.ciclo,
            "epocas_plantio": self.epocas_plantio,
            "exigencia_nutricional": self.exigencia_nutricional,
            "sombreamento": self.sombreamento,
            "pragas": self.pragas,
            "doencas": self.doencas,
            "controle_natural": self.controle_natural,
            "cobertura_solo": self.cobertura_solo,
            "diametro_copa": self.diametro_copa,
            "atrai_polinizadores": self.atrai_polinizadores,
            "interacao_outros": self.interacao_outros,
            "resistencia": self.resistencia,
            "tempo_colheita": self.tempo_colheita,
            "icone": self.icone,
            "atributos_extras": self.atributos_extras,
        }

if __name__ == "__main__":
    caminho_json = os.path.join(os.path.dirname(__file__), "culturas.json")

    novas_culturas = [
                Cultura(
            nome="ABACAXI",
            tipo="Frutífera",
            classificacao_agronomica="Comercial e Industrial",
            classificacao_morfologica="Herbácea perene de porte médio",
            sinergias=["Feijão-guandu", "Crotalária", "Mamona"],
            antagonismos=["Cebola", "Alho"],
            tempo_crescimento=450,
            rendimento=35,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "bem drenado e leve"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="21–30°C",
            faixa_ph="5.0–6.0",
            porte="Médio",
            ciclo="Perene (15 a 24 meses)",
            epocas_plantio=["Outubro a Março (Minas Gerais)"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Tripes", "Cochonilhas", "Ácaros"],
            doencas=["Fusariose", "Murcha bacteriana", "Podridões pós-colheita"],
            controle_natural=["Uso de mudas sadias", "Adubação equilibrada", "Cobertura morta"],
            cobertura_solo=4,
            diametro_copa = 1,
            atrai_polinizadores="Não",
            interacao_outros="Melhora aproveitamento da área em consórcios",
            resistencia="Moderada à seca",
            tempo_colheita="15 a 24 meses",
            icone="🍍"
        ),
                Cultura(
            nome="ABOBRINHA-MENINA",
            tipo="Hortaliça",
            classificacao_agronomica="Mesa e Comercial",
            classificacao_morfologica="Planta rasteira ou semi-ereta, herbácea anual",
            sinergias=["Milho", "Feijão", "Crotalária"],
            antagonismos=["Pepino", "Melancia", "Outras cucurbitáceas em rotação imediata"],
            tempo_crescimento=90,
            rendimento=24,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "leve, fértil e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="22–30°C",
            faixa_ph="5.5–6.7",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Ano todo (em clima quente)", "Agosto a Março (ameno)", "Setembro a Fevereiro (frio)"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Broca-das-cucurbitáceas", "Lagartas", "Pulgões"],
            doencas=["Oídio", "Míldio", "Antracnose", "Podridões"],
            controle_natural=["Trichogramma spp.", "Telenomus sp.", "Rotação de culturas", "Cobertura morta"],
            cobertura_solo=4,
            diametro_copa = 1.5,
            atrai_polinizadores="Sim",
            interacao_outros="Favorece controle biológico e ocupa bem o solo",
            resistencia="Sensível a geadas, tolerante ao calor",
            tempo_colheita="70 a 90 dias",
            icone="🥒"
        ),
                Cultura(
            nome="AGRIÃO",
            tipo="Hortaliça folhosa",
            classificacao_agronomica="Comercial e Medicinal",
            classificacao_morfologica="Planta herbácea rasteira ou semi-aquática",
            sinergias=["Cebolinha", "Alface", "Salsinha"],
            antagonismos=["Coentro"],  # Pode competir por nutrientes e sombra
            tempo_crescimento=60,
            rendimento=20,
            necessidades={"sol": "pleno a meia-sombra", "agua": "alta", "solo": "úmido, fértil e bem drenado"},
            necessidade_luz="pleno a parcial",
            necessidade_hidrica="alta",
            temperatura_ideal="15–20°C",
            faixa_ph="6.0–6.8",
            porte="Baixo",
            ciclo="Anual com múltiplos cortes",
            epocas_plantio=["Março a Julho (preferencial)", "Ano todo em regiões serranas"],
            exigencia_nutricional="Alta",
            sombreamento=2,
            pragas=["Pulgões", "Lagartas", "Moluscos"],
            doencas=["Podridões", "Murchas fúngicas (ocasionalmente)"],
            controle_natural=["Água de sabão", "Urina fermentada", "Rotação de culturas"],
            cobertura_solo=3,
            diametro_copa = 0.3,
            atrai_polinizadores="Não",
            interacao_outros="Excelente para controle biológico e rotação; folhagem densa ajuda na cobertura do solo",
            resistencia="Sensível ao calor, tolerante à umidade elevada",
            tempo_colheita="40 a 70 dias",
            icone="🌿"
        ),

                Cultura(
            nome="ALFACE",
            tipo="Hortaliça folhosa",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea, folhosa de porte baixo",
            sinergias=["Cenoura", "Rabanete", "Cebolinha", "Beterraba"],
            antagonismos=["Coentro", "Salsão"],  # evitam-se pela competição ou alelopatia
            tempo_crescimento=70,
            rendimento=20,
            necessidades={"sol": "pleno", "agua": "frequente", "solo": "leve, fértil e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="7–24°C",
            faixa_ph="6.0–6.8",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Ano todo com variedade adequada", "Melhor entre fevereiro e agosto"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Pulgões", "Lesmas", "Lagartas", "Moscas-minadoras"],
            doencas=["Queima das bordas", "Míldio", "Podridão de raízes"],
            controle_natural=["Cobertura morta", "Rotação de culturas", "Cultivo protegido"],
            cobertura_solo=3,
            diametro_copa = 0.4,
            atrai_polinizadores="Não",
            interacao_outros="Boa para consórcios rápidos, cobertura leve do solo",
            resistencia="Sensível a calor e doenças foliares; tolera frio leve",
            tempo_colheita="60 a 80 dias",
            icone="🥬"
        ),
                Cultura(
            nome="ALHO",
            tipo="Hortaliça",
            classificacao_agronomica="Comercial e Medicinal",
            classificacao_morfologica="Planta herbácea, bulbosa de pequeno porte",
            sinergias=["Cenoura", "Alface", "Morango", "Tomate"],
            antagonismos=["Ervilha", "Feijão"],
            tempo_crescimento=120,
            rendimento=15,
            necessidades={"sol": "pleno", "agua": "controlado", "solo": "bem drenado, fértil e rico em matéria orgânica"},
            necessidade_luz="pleno",
            necessidade_hidrica="baixa",
            temperatura_ideal="10–22°C (varia por fase)",
            faixa_ph="6.0–6.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Fevereiro a Maio (Centro-Sul)", "Maio (em regiões quentes e baixas altitudes)"],
            exigencia_nutricional="Alta",
            sombreamento=0,
            pragas=["Tripes", "Ácaros", "Traças de armazenamento"],
            doencas=["Ferrugem", "Podridões", "Superbrotamento"],
            controle_natural=["Rotação de culturas", "Aspersão racional", "Fumigação com fosfina"],
            cobertura_solo=3,
            diametro_copa = 0.3,
            atrai_polinizadores="Não",
            interacao_outros="Ação repelente natural contra pragas; melhora controle biológico",
            resistencia="Alta ao frio, sensível ao calor excessivo",
            tempo_colheita="110 a 130 dias",
            icone="🧄"
        ),
                Cultura(
            nome="AMENDOIM",
            tipo="Oleaginosa",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta rasteira ou ereta, anual",
            sinergias=["Milho", "Feijão", "Crotalária"],
            antagonismos=["Girassol", "Batata-doce"],  # competição por nutrientes e solo
            tempo_crescimento=120,
            rendimento=3.0,  # toneladas por hectare (média entre 2,5 e 3,5 t/ha)
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "bem drenado e fértil"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="20–30°C",
            faixa_ph="5.5–6.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Outubro a Novembro (das águas)", "Janeiro a Fevereiro (da seca)"],
            exigencia_nutricional="Alta em cálcio",
            sombreamento=0,
            pragas=["Tripes", "Cigarrinhas", "Lagartas", "Cupins", "Percevejos-de-raiz"],
            doencas=["Tombamento", "Ferrugem", "Podridões de vagens", "Contaminação por aflatoxinas"],
            controle_natural=["Inoculação com Bradyrhizobium", "Rotação de culturas", "Monitoramento de pragas"],
            cobertura_solo=2,
            diametro_copa = 0.6,
            atrai_polinizadores="Não",
            interacao_outros="Melhora estrutura do solo com fixação biológica de nitrogênio",
            resistencia="Alta à seca, sensível ao excesso de umidade",
            tempo_colheita="90 a 130 dias",
            icone="🥜"
        ),
                Cultura(
            nome="BANANA",
            tipo="Frutífera",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea perene de porte médio a alto",
            sinergias=["Cacau", "Mamona", "Crotalária"],
            antagonismos=["Batata-doce", "Girassol"],  # devido a competição e pragas comuns
            tempo_crescimento=300,
            rendimento=16,
            necessidades={"sol": "pleno", "agua": "constante", "solo": "profundo, fértil, bem drenado e úmido"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="24–30°C",
            faixa_ph="6.0–6.5",
            porte="Alto",
            ciclo="Perene (colheitas a cada 8–18 meses, dependendo da altitude)",
            epocas_plantio=["Início das chuvas (primavera)", "Ano todo em áreas irrigadas"],
            exigencia_nutricional="Muito alta",
            sombreamento=3,
            pragas=["Broca-do-rizoma", "Tripes", "Pulgões", "Abelhas (nos cachos)"],
            doencas=["Sigatoka-negra", "Mal-do-panamá", "Podridões de rizoma", "Mancha bacteriana"],
            controle_natural=["Uso de mudas sadias", "Ensacamento dos cachos", "Rotação e cobertura morta"],
            cobertura_solo=4,
            diametro_copa = 3,
            atrai_polinizadores="Não",
            interacao_outros="Fornece sombra e proteção a culturas menores; indicada em sistemas agroflorestais",
            resistencia="Sensível a ventos e doenças fúngicas; moderada à seca",
            tempo_colheita="8 a 18 meses",
            icone="🍌"
        ),
               Cultura(
            nome="BATATA",
            tipo="Hortaliça tuberosa",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea de ciclo anual, com tubérculos subterrâneos",
            sinergias=["Alface", "Cenoura", "Milho"],
            antagonismos=["Girassol", "Bananeira"],
            tempo_crescimento=110,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "controlada", "solo": "profundo, fértil, bem drenado e corrigido"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada a alta",
            temperatura_ideal="10–25°C (noturna ideal até 18°C)",
            faixa_ph="5.5–6.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Setembro a Novembro (águas)", "Fevereiro a Abril (seca)", "Maio a Julho (inverno)"],
            exigencia_nutricional="Muito alta",
            sombreamento=1,
            pragas=["Traça-da-batata", "Pulgões", "Lagarta-alfinete", "Larva-arame", "Mosca-minadora"],
            doencas=["Requeima", "Pinta-preta", "Podridões", "Murcha bacteriana", "Manchas internas"],
            controle_natural=["Rotação de culturas", "Cultivares resistentes", "Irrigação controlada", "Cobertura morta"],
            cobertura_solo=3,
            diametro_copa = 0.5,
            atrai_polinizadores="Não",
            interacao_outros="Planta exigente, ideal para rotação e cobertura rápida do solo",
            resistencia="Sensível a excesso de umidade e geadas; moderada à seca",
            tempo_colheita="90 a 115 dias",
            icone="🥔"
        ),
                Cultura(
            nome="BATATA-DOCE",
            tipo="Raiz e tubérculo",
            classificacao_agronomica="Mesa, Indústria e Forragem",
            classificacao_morfologica="Planta rasteira, herbácea perene de ciclo anual",
            sinergias=["Milho", "Feijão", "Abóbora"],
            antagonismos=["Bananeira", "Amendoim"],
            tempo_crescimento=120,
            rendimento=20,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "leve, profundo, fértil e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="24–28°C",
            faixa_ph="5.5–6.5",
            porte="Rasteiro",
            ciclo="Anual",
            epocas_plantio=["Primavera-verão", "Outono com irrigação"],
            exigencia_nutricional="Moderada",
            sombreamento=2,
            pragas=["Broca-da-raiz", "Broca-do-caule", "Cupins"],
            doencas=["Mal-do-pé", "Podridão mole", "Nematoides"],
            controle_natural=["Rotação de culturas", "Plantio de ramas sadias", "Cobertura morta"],
            cobertura_solo=4,
            diametro_copa=1.2,
            atrai_polinizadores="Não",
            interacao_outros="Boa cobertura do solo, melhora estrutura e fertilidade",
            resistencia="Alta à seca, moderada a doenças",
            tempo_colheita="100 a 150 dias",
            icone="🍠"
        ),
        Cultura(
            nome="BERINJELA",
            tipo="Hortaliça-fruto",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Herbácea semi-arbustiva de ciclo anual",
            sinergias=["Cenoura", "Alface", "Feijão-vagem"],
            antagonismos=["Tomate", "Batata", "Pimentão"],  # todos solanáceas
            tempo_crescimento=110,
            rendimento=30,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "bem drenado, fértil e com pH entre 6 e 6.3"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="18–25°C",
            faixa_ph="6.0–6.3",
            porte="Médio",
            ciclo="Anual",
            epocas_plantio=["Outono em clima quente", "Primavera-verão em clima ameno"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Mosca-branca", "Pulgões", "Broca", "Ácaros"],
            doencas=["Murcha bacteriana", "Antracnose", "Podridões", "Manchas foliares"],
            controle_natural=["Rotação de culturas", "Tutoriamento", "Cobertura morta", "Inseticidas seletivos"],
            cobertura_solo=3,
            diametro_copa=1.0,
            atrai_polinizadores="Sim",
            interacao_outros="Pode ser conduzida verticalmente; se adapta bem ao consórcio",
            resistencia="Moderada a pragas e doenças; sensível ao encharcamento",
            tempo_colheita="90 a 110 dias",
            icone="🍆"
        ),
        Cultura(
            nome="BETERRABA",
            tipo="Raiz e tubérculo",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Herbácea de porte baixo, bianual cultivada como anual",
            sinergias=["Alface", "Cebolinha", "Cenoura"],
            antagonismos=["Salsinha", "Espinafre"],
            tempo_crescimento=70,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "leve, fértil, bem drenado, pH 6–7"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="10–20°C",
            faixa_ph="6.0–7.0",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Outono-inverno", "Ano todo em clima ameno"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Lagartas", "Pulgões", "Vaquinhas", "Ácaros"],
            doencas=["Tombamento", "Mancha das folhas", "Míldio", "Nematoides"],
            controle_natural=["Rotação de culturas", "Sementes tratadas", "Cobertura morta", "Solarização"],
            cobertura_solo=3,
            diametro_copa=0.4,
            atrai_polinizadores="Não",
            interacao_outros="Crescimento rápido, favorece controle biológico",
            resistencia="Tolerante a geadas fracas; sensível a calor excessivo",
            tempo_colheita="60 a 80 dias",
            icone="🫐"
        ),
        Cultura(
            nome="BRÓCOLIS",
            tipo="Hortaliça folhosa",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea com inflorescência comestível",
            sinergias=["Alface", "Cenoura", "Cebola"],
            antagonismos=["Repolho", "Couve-flor"],  # competição por nutrientes
            tempo_crescimento=90,
            rendimento=12,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "profundo, fértil, bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="10–22°C",
            faixa_ph="6.0–6.8",
            porte="Médio",
            ciclo="Anual",
            epocas_plantio=["Ano todo, preferencialmente entre março e agosto"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Lagartas", "Pulgões"],
            doencas=["Míldio", "Manchas foliares", "Podridões"],
            controle_natural=["Rotação de culturas", "Mudas sadias", "Cobertura morta"],
            cobertura_solo=3,
            diametro_copa=0.8,
            atrai_polinizadores="Sim",
            interacao_outros="Boa para diversificação alimentar e produção intensiva",
            resistencia="Sensível a calor excessivo e pragas foliares",
            tempo_colheita="70 a 100 dias",
            icone="🥦"
        ),
        Cultura(
            nome="CEBOLA",
            tipo="Hortaliça bulbo",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea bienal, cultivada como anual",
            sinergias=["Cenoura", "Alface", "Beterraba", "Tomilho"],
            antagonismos=["Feijão", "Ervilha"],
            tempo_crescimento=140,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "moderada", "solo": "leve, fértil, bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="13–25°C",
            faixa_ph="6.0–6.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Maio a Julho", "Novembro a Janeiro"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Tripes", "Lagarta-rosca", "Ácaro da cebola"],
            doencas=["Míldio", "Manchas foliares", "Podridões", "Mal-do-pescoço"],
            controle_natural=["Rotação de culturas", "Cura dos bulbos", "Cobertura morta"],
            cobertura_solo=3,
            diametro_copa=0.4,
            atrai_polinizadores="Não",
            interacao_outros="Melhora controle de pragas em consórcios",
            resistencia="Moderada à seca, sensível à umidade e florescimento precoce",
            tempo_colheita="90 a 150 dias",
            icone="🧅"
        ),
        Cultura(
            nome="CENOURA",
            tipo="Raiz e tubérculo",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea de porte baixo e raízes engrossadas",
            sinergias=["Alface", "Cebola", "Cebolinha"],
            antagonismos=["Salsinha", "Coentro"],
            tempo_crescimento=110,
            rendimento=35,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "fácil de revolver, fértil e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="16–25°C",
            faixa_ph="6.0–6.8",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Ano todo com cultivares adaptadas", "Melhor entre março e agosto"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Lagarta-rosca", "Pulgão"],
            doencas=["Queima-das-folhas", "Manchas", "Podridões"],
            controle_natural=["Rotação de culturas", "Cobertura morta", "Plantio em época adequada"],
            cobertura_solo=3,
            diametro_copa=0.3,
            atrai_polinizadores="Não",
            interacao_outros="Boa para rotação de culturas e ocupação eficiente do solo",
            resistencia="Boa tolerância ao frio, sensível à vernalização precoce",
            tempo_colheita="80 a 120 dias",
            icone="🥕"
        ),
        Cultura(
            nome="COUVE-FLOR",
            tipo="Hortaliça",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea com inflorescência comestível",
            sinergias=["Alface", "Cenoura", "Cebola"],
            antagonismos=["Repolho", "Rabanete"],
            tempo_crescimento=90,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "profundo, fértil, pH 6–6.8, rico em matéria orgânica"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="15–22°C",
            faixa_ph="6.0–6.8",
            porte="Médio",
            ciclo="Anual",
            epocas_plantio=["Ano todo (com variedade adequada)", "Melhor entre março e agosto"],
            exigencia_nutricional="Muito alta",
            sombreamento=1,
            pragas=["Lagartas", "Pulgões", "Traças"],
            doencas=["Míldio", "Manchas foliares", "Podridões"],
            controle_natural=["Cobertura morta", "Rotação de culturas", "Inseticidas biológicos"],
            cobertura_solo=3,
            diametro_copa=0.8,
            atrai_polinizadores="Sim",
            interacao_outros="Exige controle térmico e nutricional, ótimo para produção intensiva",
            resistencia="Sensível ao calor, tolera bem geadas leves",
            tempo_colheita="70 a 100 dias",
            icone="🥦"
        ),
        Cultura(
            nome="ERVILHA",
            tipo="Leguminosa",
            classificacao_agronomica="Alimentar e Industrial",
            classificacao_morfologica="Planta herbácea trepadeira ou ereta, anual",
            sinergias=["Milho", "Cenoura", "Alface"],
            antagonismos=["Cebola", "Alho"],
            tempo_crescimento=100,
            rendimento=2.0,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "fértil, bem drenado e com boa matéria orgânica"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="13–20°C",
            faixa_ph="6.0–6.8",
            porte="Baixo a médio",
            ciclo="Anual",
            epocas_plantio=["Março a Maio (Minas Gerais)", "Ano todo em clima ameno com irrigação"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Tripes", "Lagartas", "Pulgões"],
            doencas=["Oídio", "Mofo-branco", "Ascoquita", "Vira-cabeça"],
            controle_natural=["Cultivares resistentes", "Irrigação controlada", "Rotação de culturas"],
            cobertura_solo=2,
            diametro_copa=0.5,
            atrai_polinizadores="Não",
            interacao_outros="Fixadora de nitrogênio; ótima para consórcios e recuperação de solos",
            resistencia="Boa tolerância ao frio, sensível a calor excessivo",
            tempo_colheita="80 a 120 dias",
            icone="🌿"
        ),
        Cultura(
            nome="FEIJÃO-CARIOCA",
            tipo="Leguminosa",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Planta herbácea de ciclo curto, anual",
            sinergias=["Milho", "Café", "Mandioca"],
            antagonismos=["Soja (quando há vírus presente)", "Alho"],
            tempo_crescimento=90,
            rendimento=2.5,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "leve, fértil, bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="18–24°C",
            faixa_ph="5.8–6.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Primavera, Verão, Outono, Inverno (com irrigação)"],
            exigencia_nutricional="Alta",
            sombreamento=1,
            pragas=["Cigarrinha-verde", "Mosca-branca", "Pulgões", "Lagartas"],
            doencas=["Mofo-branco", "Murcha-de-fusarium", "Ferrugem"],
            controle_natural=["Rotação de culturas", "Cobertura morta", "Insumos biológicos"],
            cobertura_solo=3,
            diametro_copa=0.4,
            atrai_polinizadores="Não",
            interacao_outros="Melhora fixação biológica de nitrogênio no solo",
            resistencia="Boa tolerância ao frio, sensível à umidade em excesso",
            tempo_colheita="80 a 100 dias",
            icone="🫘"
        ),
        Cultura(
            nome="GRÃO-DE-BICO",
            tipo="Leguminosa",
            classificacao_agronomica="Alimentar e Industrial",
            classificacao_morfologica="Planta herbácea anual de ciclo médio",
            sinergias=["Cenoura", "Alface", "Coentro"],
            antagonismos=["Feijão", "Soja (com vírus)"],
            tempo_crescimento=120,
            rendimento=20,
            necessidades={"sol": "pleno", "agua": "baixa a moderada", "solo": "arenoso ou bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="baixa",
            temperatura_ideal="15–30°C",
            faixa_ph="5.5–8.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Abril a Maio (regiões secas com irrigação)"],
            exigencia_nutricional="Moderada (NPK)",
            sombreamento=1,
            pragas=["Lagartas", "Minadores", "Gorgulhos", "Bruchus spp."],
            doencas=["Murcha-de-fusarium", "Mofo-cinzento", "Mancha-de-ascoquita"],
            controle_natural=["Tratamento de sementes", "Rotação", "Controle de umidade"],
            cobertura_solo=2,
            diametro_copa=0.5,
            atrai_polinizadores="Não",
            interacao_outros="Fixadora de nitrogênio; útil em solos pobres e áridos",
            resistencia="Alta à seca, sensível à salinidade e encharcamento",
            tempo_colheita="100 a 150 dias",
            icone="🧆"
        ),
        Cultura(
            nome="LENTILHA",
            tipo="Leguminosa",
            classificacao_agronomica="Grão alimentar e cobertura",
            classificacao_morfologica="Planta herbácea de pequeno porte",
            sinergias=["Cenoura", "Milho", "Cebola"],
            antagonismos=["Tomate", "Berinjela"],
            tempo_crescimento=105,
            rendimento=16,
            necessidades={"sol": "pleno", "agua": "baixa", "solo": "bem drenado, fértil, pH neutro a levemente ácido"},
            necessidade_luz="pleno",
            necessidade_hidrica="baixa",
            temperatura_ideal="13–21°C (até 25°C)",
            faixa_ph="6.0–7.5",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Maio a Junho (regiões frias)"],
            exigencia_nutricional="Baixa",
            sombreamento=1,
            pragas=["Bruchus lentis", "Gorgulhos", "Lagartas"],
            doencas=["Murcha", "Mofo", "Podridões radiculares"],
            controle_natural=["Rotação de culturas", "Sementes tratadas", "Boa drenagem"],
            cobertura_solo=2,
            diametro_copa=0.4,
            atrai_polinizadores="Não",
            interacao_outros="Fixadora de nitrogênio, ótima para solos pobres",
            resistencia="Alta à seca, sensível ao excesso de umidade",
            tempo_colheita="100 a 120 dias",
            icone="🌰"
        ),
        Cultura(
            nome="MAÇÃ",
            tipo="Frutífera",
            classificacao_agronomica="Comercial e Alimentar",
            classificacao_morfologica="Árvore caducifólia de clima temperado",
            sinergias=["Cebola", "Alface", "Trigo"],
            antagonismos=["Girassol", "Tomate"],
            tempo_crescimento=240,
            rendimento=30,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "profundo, fértil, bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="15–20°C",
            faixa_ph="5.3–6.0",
            porte="Médio a alto",
            ciclo="Perene",
            epocas_plantio=["Inverno (Julho a Agosto)"],
            exigencia_nutricional="Alta (Cálcio, Potássio, Nitrogênio)",
            sombreamento=3,
            pragas=["Mosca-das-frutas", "Ácaros", "Pulgões", "Lagartas"],
            doencas=["Sarna", "Oídio", "Podridão", "Míldio"],
            controle_natural=["Poda de formação", "Polinizadores naturais", "Aplicação de caldas"],
            cobertura_solo=4,
            diametro_copa=3.5,
            atrai_polinizadores="Sim",
            interacao_outros="Requer cultivares polinizadoras próximas; boa para reflorestamento produtivo",
            resistencia="Média a pragas, sensível ao calor",
            tempo_colheita="6 a 8 meses após a florada",
            icone="🍎"
        ),
        Cultura(
            nome="MANDIOCA",
            tipo="Raiz e tubérculo",
            classificacao_agronomica="Mesa, Indústria, Forragem",
            classificacao_morfologica="Arbusto de porte médio",
            sinergias=["Milho", "Feijão", "Crotalária"],
            antagonismos=["Tomate", "Berinjela"],
            tempo_crescimento=360,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "profundo e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="25–30°C",
            faixa_ph="5.5–6.5",
            porte="Médio",
            ciclo="Perene (colheita entre 12 e 24 meses)",
            epocas_plantio=["Outubro a Dezembro (Cerrado)", "Junho a Setembro (Zona da Mata)"],
            exigencia_nutricional="Moderada",
            sombreamento=2,
            pragas=["Mandarová", "Cupins", "Formigas", "Ácaros", "Mosca-do-broto", "Tripes"],
            doencas=["Bacteriose", "Podridões radiculares", "Mosaico-comum"],
            controle_natural=["Bacillus thuringiensis", "Rotação de culturas", "Variedades resistentes"],
            cobertura_solo=3,
            diametro_copa = 1.2,
            atrai_polinizadores="Não",
            interacao_outros="Boa adaptabilidade e rusticidade; tolera solos pobres",
            resistencia="Alta à seca, moderada a doenças",
            tempo_colheita="12 a 24 meses",
            icone="🌱"
        ),
        Cultura(
            nome="MILHO VERDE",
            tipo="Cereal",
            classificacao_agronomica="Mesa e Indústria",
            classificacao_morfologica="Herbácea anual de porte alto",
            sinergias=["Feijão", "Cucurbitáceas", "Mandioca"],
            antagonismos=["Tomate", "Berinjela"],
            tempo_crescimento=90,
            rendimento=40,
            necessidades={"sol": "pleno", "agua": "regular", "solo": "fértil e bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="20–30°C",
            faixa_ph="5.5–6.8",
            porte="Alto",
            ciclo="Anual",
            epocas_plantio=["Ano todo com irrigação"],
            exigencia_nutricional="Alta",
            sombreamento=0,
            pragas=["Lagarta-do-cartucho", "Cigarrinha-do-milho"],
            doencas=["Manchas foliares", "Ferrugens"],
            controle_natural=["Trichogramma", "Controle biológico", "Rotação de culturas"],
            cobertura_solo=2,
            diametro_copa=0.7,
            atrai_polinizadores="Não",
            interacao_outros="Boa cobertura de solo após colheita",
            resistencia="Moderada a pragas",
            tempo_colheita="90 dias",
            icone="🌽"
        ),
        Cultura(
            nome="SOJA",
            tipo="Leguminosa",
            classificacao_agronomica="Grãos",
            classificacao_morfologica="Herbácea anual de porte baixo",
            sinergias=["Milho", "Feijão", "Crotalária"],
            antagonismos=["Alho", "Cebola"],
            tempo_crescimento=100,
            rendimento=50,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "bem drenado e fértil"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="20–30°C",
            faixa_ph="5.5–6.8",
            porte="Baixo",
            ciclo="Anual",
            epocas_plantio=["Primavera", "Verão"],
            exigencia_nutricional="Alta",
            sombreamento=0,
            pragas=["Lagartas", "Percevejos"],
            doencas=["Ferrugem asiática", "Oídio"],
            controle_natural=["Rotação de culturas", "Controle biológico"],
            cobertura_solo=2,
            diametro_copa=0.8,
            atrai_polinizadores="Sim",
            interacao_outros="Fixadora de nitrogênio",
            resistencia="Alta a seca",
            tempo_colheita="100 dias",
            icone="🌿"
        ),
        Cultura(
            nome="TOMATE",
            tipo="Frutífera",
            classificacao_agronomica="Mesa e Indústria",
            classificacao_morfologica="Herbácea anual de crescimento determinado ou indeterminado",
            sinergias=["Cenoura", "Cebolinha"],
            antagonismos=["Batata", "Berinjela"],
            tempo_crescimento=120,
            rendimento=60,
            necessidades={"sol": "pleno", "agua": "frequente", "solo": "bem drenado e fértil"},
            necessidade_luz="pleno",
            necessidade_hidrica="alta",
            temperatura_ideal="21–24°C (ideal), sensível acima de 30°C",
            faixa_ph="5.5–6.5",
            porte="Médio",
            ciclo="Anual",
            epocas_plantio=["Ano todo em regiões adequadas"],
            exigencia_nutricional="Alta",
            sombreamento=0,
            pragas=["Pulgões", "Tripes", "Mosca-branca"],
            doencas=["Míldio", "Oídio", "Podridões"],
            controle_natural=["Rotação de culturas", "Cobertura morta", "Predadores naturais"],
            cobertura_solo=3,
            diametro_copa=1.5,
            atrai_polinizadores="Não",
            interacao_outros="Demanda alta por nutrientes, influência sobre qualidade do solo",
            resistencia="Baixa a doenças foliares",
            tempo_colheita="85 a 125 dias",
            icone="🍅"
        ),
        Cultura(
            nome="TRIGO",
            tipo="Cereal",
            classificacao_agronomica="Grãos e panificação",
            classificacao_morfologica="Herbácea anual de porte médio",
            sinergias=["Soja", "Ervilha", "Feijão"],
            antagonismos=["Cebola", "Tomate"],
            tempo_crescimento=120,
            rendimento=50,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "bem drenado, fértil, pH corrigido"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="18–24°C (ótimo); tolera até 30°C",
            faixa_ph="5.8–6.5",
            porte="Médio",
            ciclo="Anual",
            epocas_plantio=["Janeiro a Junho (varia por altitude e irrigação)"],
            exigencia_nutricional="Alta",
            sombreamento=0,
            pragas=["Lagarta-do-trigo", "Percevejo", "Pulgões"],
            doencas=["Ferrugem", "Míldio", "Oídio", "Manchas foliares"],
            controle_natural=["Rotação de culturas", "Cobertura morta", "Sementes tratadas"],
            cobertura_solo=3,
            diametro_copa=0.5,
            atrai_polinizadores="Não",
            interacao_outros="Boa cobertura vegetal e fonte de palhada em plantio direto",
            resistencia="Moderada a seca, sensível a geadas na floração",
            tempo_colheita="90 a 130 dias",
            icone="🌾"
        ),
        Cultura(
            nome="UVA",
            tipo="Frutífera",
            classificacao_agronomica="Mesa, vinho e sucos",
            classificacao_morfologica="Trepadeira lenhosa perene",
            sinergias=["Alho", "Cebola", "Capim-limão"],
            antagonismos=["Batata", "Cenoura"],
            tempo_crescimento=240,
            rendimento=25,
            necessidades={"sol": "pleno", "agua": "moderado", "solo": "profundo, fértil, bem drenado"},
            necessidade_luz="pleno",
            necessidade_hidrica="moderada",
            temperatura_ideal="15–30°C",
            faixa_ph="5.5–6.5",
            porte="Trepadeira",
            ciclo="Perene",
            epocas_plantio=["Outono a primavera, com poda programada"],
            exigencia_nutricional="Alta",
            sombreamento=3,
            pragas=["Tripes", "Ácaros", "Cochonilhas", "Lagartas"],
            doencas=["Míldio", "Oídio", "Podridões", "Ferrugem"],
            controle_natural=["Poda adequada", "Cobertura do solo", "Aplicações foliares equilibradas"],
            cobertura_solo=4,
            diametro_copa=3,
            atrai_polinizadores="Sim",
            interacao_outros="Importante na agricultura familiar e vinicultura; sensível ao manejo hídrico",
            resistencia="Moderada a pragas, exige cuidados com doenças fúngicas",
            tempo_colheita="6 a 10 meses após poda",
            icone="🍇"
        ),

    ]

    # Carrega o JSON existente (se houver)
    if os.path.exists(caminho_json):
        with open(caminho_json, "r", encoding="utf-8") as f:
            existentes = json.load(f)
    else:
        existentes = []

    for cultura in novas_culturas:
        existentes.append(cultura.to_dict())

    with open(caminho_json, "w", encoding="utf-8") as f:
        json.dump(existentes, f, ensure_ascii=False, indent=2)

    print("✅ Culturas adicionadas ao culturas.json com sucesso.")
